### PR TITLE
return production rule

### PR DESCRIPTION
**Pull request by ksulinski**

### CODE REVIEW

**Comment by ycfreeman** [comment]
hmm is it valid with only return statement?

**Comment by ksulinski** [comment]
What do you mean? I think that I don't understand. It's valid for 'return'
and 'return Statement'.

**Comment by ycfreeman** [comment]
hmm what i mean is a js file with only return statement inside syntactically correct?

**Comment by ksulinski** [comment]
Oh yes. It's valid ;-)

**Pull request merged**
